### ISSUE TITLE
Intrvjua 1 person

### ISSUE THREAD

**Issue by tinaforeby** [chas-academy/u01-designstudie-mario-kart-project-pioneers#7]

**Comment by WilliamLundquist** [comment]
•	Introduktion
•	Hur länge har du spelat diskgolf?
	Svar: 2 säsonger, hade spelat om jag hade haft mer tid. Men ett småbarn och ett till 	på väg så får discgolfen vänta ett par år till, 
        förutom när min kusin kommer ned och hälsar på, då 	kommer vi spela.
•	Vad fick dig att börja spela?
	Svar: Hittade discgolf, uttråkad under Corona, bodde bredvid en bana. Ute 	på promenad, såg korgarna. 
•	Vad är det bästa med diskgolf för dig?
	Svar: Trevligt sätt att umgås, man rör på sig. Valt bort golf pga kostnad, 	tröskeln för att börja spela discgolf är så otroligt lågt. 
        Hade man behövt gå med i en förening så hade jag nog inte börjat spela discgolf
•	Intresse och förväntningar
•	Vilka verktyg har du använt tidigare för att hitta information om diskgolf?
	Svar: youtube och chatgpt för att förstå regler och teknik(youtube)
•	Vad har du tyckt om de verktyg du har använt?
	Svar: Tycker det är för att lära sig teknik, det är som att lära sig 	gyminstruktioner, gå snabbare att lära sig via video. Regler är 
        värdelöst för 	denna plattformen, då hade det varit bättre med regler i textform, när kusin 	försöker fuska. 
•	Finns det något du saknar i de verktyg du använder idag?
	Svar: Främst regeltolkningar, sektioner kring regler. går ju att använda 	chatgp, 	men dom är inte alltid så pålitliga.
•	Har du några favoritverktyg eller webbplatser som du rekommenderar? Vad uppskattar du med dem? -->
•	Behov
•	Hur skulle du vilja upptäcka nya banor?
	Svar: Vill absolut hitta nya banor, en stor del till sporten i sig att fortsätta 	utmana sig. Likt en karta för lekplatser som finns i 
        göteborg. (Play way) Tror. Där man kan se bilder och recensionerna på banor av andra användare.
	Svar: Googlar idag för att hitta nya banor (frisbeegolf) Svårt man får typ 	alltid upp google maps, 50% av banorna finns inte längre eller så har dom 	aldrig underhållts. Korgarna kanske inte finns kvar. Man ser inte heller om 	banan kostar pengar eller inte
•	Webbplatsens funktioner
•	Vad skulle du vilja se som primärfunktion för en webbplats om discgolf?
	Svar: Officiella regler, kartor för att hitta banor som är uppdaterd, Scorekort 	för att slippa göra ett eget i anteckningar. Gärna 
        knutet till banan.  	Vägvisning på banan för skyltningen är bristfällig på många banor, 	Community för att träffa andra spelare.
•	Vilka funktioner skulle du vilja se på en dedikerad diskgolf-webbplats? (t.ex. kartor, forum, evenemangsöversikter)? -->
•	Vilken information skulle vara mest värdefull för dig på en diskgolf-webbplats? (t.ex. banrecensioner, tävlingar, strategier, 
        instruktionsvideor)?
	Svar: För mig är discgolf en hobby och jag vill helst se fokus på det folkliga	Tävlingar och instruktionsvideo hade bara gett 
        negativ känsla på sidan. Vill 	hålla det folkligt.
•	Hur skulle du använda informationen på hemsidan?
•	Hur skulle du vilja upptäcka nya banor?
         Det vore bra om man hade en kartvy men förutom information om banan också finns användarrecenensioner och foton på banan. 
         Många banor som finns på google idag existerar inte i verkligheten eller så är dom inte underhållna överhuvudtaget, och jag som 
         inte har bil så tar det mig en stund att åka till dom olika banorna, och man blir rejält besviken om banan är uselt skött efter en lång 
         resa.
•	Hur skulle du vilja bli meddelad när en nyhet eller ny bana kommer upp?
	Svar: Ja på startsidan, varför inte. Ska inte dominera sidan dock. Har inte 	gått dit för att upptäcka saker och hamnat på sidan.
•	Finns det några webbplatser inom sport, spel eller andra relaterade områden som du tycker är bra? Vad uppskattar du med dem?
	Svar: Googlar på allsvenskan, fokus på det. Allt kring Nyheter genom twitter. 
•	Användning av webbplatser
•	Hur letar du vanligtvis efter ny information om diskgolf och relaterade aktiviteter?
	Google.
•	Vilka faktorer gör en webbplats användarvänlig enligt dig, särskilt inom sport eller spel?
	Svar: Använder sig av google för att söka mer på det ordet för att hitta 		sajter, tex disc ska jag söka. Tycker det är en bättre 
         källa för information. 	Kanske om man hade halkat in som på reddit,  community drivet.
	Google är smidigaste sättet. Försök kasta ut ett så stort nät som möjligt. 	Anledningen att jag inte går till en specifik sida är för att 
        alla dom 	jornalisterna är köpta och delar sin åsikt positivt för just den produkten.
•	Allmänna frågor
•	Finns det något du tycker saknas på befintliga diskgolf-sajter eller appar?
•	Hur skulle du beskriva en idealisk webbplats för diskgolf?
•	Vad skulle få dig att återvända till webbplatsen regelbundet?
        Svar: Om sidan erbjuder typ scorecard och sådant som man kan använda sig av medan man spelar.
•	Vad skulle få dig att rekommendera webbplatsen till andra spelare?
	Svar: Unikt värde, Community, banrecension, möjligt att dela banor med 	andra genom en länk
•	Har du något annat att lägga till utöver det jag frågat dig idag?
	Studera hur människor faktiskt använder sidan.

**Comment by WilliamLundquist** [comment]
## Intervjumall för nybörjare (nyfikna på discgolf)

### Johannes är i målgruppen för erfarna spelare.


## Intervjumall för erfarna spelare (har spelat diskgolf)

1. **Introduktion**
   - Hur länge har du spelat diskgolf?

2 säsonger, hade spelat om jag hade haft mer tid. Men ett småbarn och ett till 	på väg så får discgolfen vänta ett par år till, förutom när min kusin kommer ned och hälsar på, då kommer vi spela.
   - Vad fick dig att börja spela?

Hittade discgolf, uttråkad under Corona, bodde bredvid en bana. Ute 	på promenad, såg korgarna. 
   - Vad är det bästa med diskgolf för dig?

Trevligt sätt att umgås, man rör på sig. Valt bort golf pga kostnad, tröskeln för att börja spela discgolf är så otroligt lågt. Hade man behövt gå med i en förening så hade jag nog inte börjat spela discgolf

2. **Intresse och förväntningar**
   - Vilka verktyg har du använt tidigare för att hitta information om diskgolf?

Youtube för teknikövningar och recensioner, chatgpt för regler.

   - Vad har du tyckt om de verktyg du har använt?

Tycker det är för att lära sig teknik, det är som att lära sig 	gyminstruktioner, gå snabbare att lära sig via video. Regler är värdelöst för 	denna plattformen, då hade det varit bättre med regler i textform, när kusin försöker fuska. 

   - Finns det något du saknar i de verktyg du använder idag?
Främst regeltolkningar, sektioner kring regler. går ju att använda chatgp, men dom är inte alltid så pålitliga.

   - Har du några favoritverktyg eller webbplatser som du rekommenderar? Vad uppskattar du med dem?

Nej

3. **Behov**
   - Hur skulle du vilja upptäcka nya banor?

Vill absolut hitta nya banor, en stor del till sporten i sig att fortsätta 	utmana sig. Likt en karta för lekplatser som finns i göteborg. (Play way) Tror. Där man kan se bilder och recensionerna på banor av andra användare. 
Googlar idag för att hitta nya banor (frisbeegolf) Svårt man får typ alltid upp google maps, 50% av banorna finns inte längre eller så har dom aldrig underhållts. Korgarna kanske inte finns kvar. Man ser inte heller om banan kostar pengar eller inte

4. **Webbplatsens funktioner**
   - Vad skulle du vilja se som primärfunktion för en webbplats om discgolf?

Officiella regler, kartor för att hitta banor som är uppdaterd, Scorekort för att slippa göra ett eget i anteckningar. Gärna knutet till banan.  Vägvisning på banan för skyltningen är bristfällig på många banor, 	Community för att träffa andra spelare.


   - Vilken information skulle vara mest värdefull för dig på en diskgolf-webbplats? (t.ex.    banrecensioner, tävlingar, strategier, instruktionsvideor)?

För mig är discgolf en hobby och jag vill helst se fokus på det folkliga	Tävlingar och instruktionsvideo hade bara gett negativ känsla på sidan. Vill 	hålla det folkligt.
   
   - Hur skulle du vilja upptäcka nya banor?

Det vore bra om man hade en kartvy men förutom information om banan också finns användarrecenensioner och foton på banan. Många banor som finns på google idag existerar inte i verkligheten eller så är dom inte underhållna överhuvudtaget, och jag som inte har bil så tar det mig en stund att åka till dom olika banorna, och man blir rejält besviken om banan är uselt skött efter en lång resa

   - Hur skulle du vilja bli meddelad när en nyhet eller ny bana kommer upp?

på startsidan, varför inte. Ska inte dominera sidan dock. 

   - Finns det några webbplatser inom sport, spel eller andra relaterade områden som du tycker är bra? Vad uppskattar du med dem?

Googlar på allsvenskan, fokus på det. Allt kring Nyheter genom twitter. Brett sök område, vet man vad man ska söka på så hittar man oftast det lättast på google.

5. **Användning av webbplatser**
   - Hur letar du vanligtvis efter ny information om diskgolf och relaterade aktiviteter?

Google

   - Vilka faktorer gör en webbplats användarvänlig enligt dig, särskilt inom sport eller spel?

Använder sig av google för att söka mer på det ordet för att hitta sajter, tex disc ska jag söka. Tycker det är en bättre källa för information. Kanske om man hade halkat in som på reddit, community drivet.
Google är smidigaste sättet. Försök kasta ut ett så stort nät som möjligt. Anledningen att jag inte går till en specifik sida är för att alla dom jornalisterna är köpta och delar sin åsikt positivt för just den produkten


6. **Allmänna frågor**

   - Vad skulle få dig att återvända till webbplatsen regelbundet?

Om sidan erbjuder typ scorecard och sådant som man kan använda sig av medan man spelar.

   - Vad skulle få dig att rekommendera webbplatsen till andra spelare?

Unikt värde, Community, banrecension, möjligt att dela banor med andra genom en länk
